/**
 * Demo inventory shown when no Supabase/Blob listings are published yet.
 *
 * Real published listings always take precedence — these only fill the
 * portfolio so the product is reviewable before inventory is loaded.
 */

const img = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1400&q=80`;

const INTERIORS = [
  "1545324418-cc1a3fa10c00",
  "1502672260266-1c1ef2d93688",
  "1522708323590-d24dbb6b0267",
  "1560448204-e02f11c3d0e2",
  "1493809842364-78817add7ffb",
  "1560185007-cde436f6a4d0",
];

const gallery = (offset: number) =>
  [0, 1, 2].map((i) => img(INTERIORS[(offset + i) % INTERIORS.length]));

export const SEED_PROPERTIES = [
  {
    id: "rbr-001",
    slug: "marina-vista-2br-emaar-beachfront",
    title: "Marina Vista — 2 Bed Sea View",
    location: "Emaar Beachfront, Dubai",
    locality: "Emaar Beachfront",
    community: "Emaar Beachfront",
    emirate: "Dubai",
    price: "3,450,000",
    priceQualifier: "AED",
    purpose: "For Sale",
    type: "Apartment",
    constructionStatus: "Handed Over",
    bedrooms: 2,
    bathrooms: 3,
    area: "1,180 sq ft",
    floor: "32 of 60",
    parking: "1 covered bay",
    furnishing: "Unfurnished",
    status: "Live",
    views: 412,
    enquiries: 18,
    published: "2026-06-02",
    description:
      "A corner two-bedroom on a high floor at Marina Vista, with uninterrupted views across the Gulf and the marina skyline. Handed over and vacant on transfer, so it suits either an end-user moving in directly or an investor targeting short-let yield on a beachfront address.",
    highlights: [
      "Direct private beach access",
      "Vacant on transfer",
      "Corner layout with dual aspect",
      "Emaar-managed building",
    ],
    images: gallery(0),
    developer: "Emaar",
    ownership: "Freehold",
    expectedYield: "6.4%",
    serviceCharge: "AED 18 / sq ft",
    reraVerified: true,
    featured: true,
    commissionCovered: false,
    amenities: [
      "Private beach",
      "Infinity pool",
      "Gymnasium",
      "24/7 concierge",
      "Covered parking",
    ],
  },
  {
    id: "rbr-002",
    slug: "creek-waters-1br-off-plan",
    title: "Creek Waters — 1 Bed Off-Plan",
    location: "Dubai Creek Harbour, Dubai",
    locality: "Dubai Creek Harbour",
    community: "Dubai Creek Harbour",
    emirate: "Dubai",
    price: "1,620,000",
    priceQualifier: "AED",
    purpose: "For Sale",
    type: "Apartment",
    constructionStatus: "Off-plan",
    possessionMonth: "September",
    possessionYear: 2027,
    bedrooms: 1,
    bathrooms: 2,
    area: "745 sq ft",
    floor: "18 of 40",
    parking: "1 allocated bay",
    furnishing: "Unfurnished",
    status: "Live",
    views: 268,
    enquiries: 12,
    published: "2026-06-18",
    description:
      "An entry-price one-bedroom in Emaar's Creek Waters tower, overlooking the creek promenade. The payment plan carries 20% past handover, which keeps the cash requirement low through construction and suits buyers building a Dubai portfolio gradually.",
    highlights: [
      "80/20 payment plan",
      "20% post-handover over 2 years",
      "Creek promenade frontage",
      "Q3 2027 handover",
    ],
    images: gallery(2),
    developer: "Emaar",
    ownership: "Freehold",
    expectedYield: "7.1%",
    handover: "Q3 2027",
    projectStage: "Under construction",
    paymentPlan: "80/20 with post-handover",
    paymentMilestones: [
      { label: "On booking", percentage: 10 },
      { label: "During construction", percentage: 70 },
      { label: "Post-handover (24 months)", percentage: 20 },
    ],
    postHandoverPaymentPlan: true,
    commissionCovered: true,
    reraVerified: true,
    featured: true,
    amenities: [
      "Infinity pool",
      "Creek-facing podium",
      "Kids play area",
      "Retail promenade",
    ],
  },
  {
    id: "rbr-003",
    slug: "damac-hills-2-4br-townhouse",
    title: "Damac Hills 2 — 4 Bed Townhouse",
    location: "Damac Hills 2, Dubai",
    locality: "Damac Hills 2",
    community: "Damac Hills",
    emirate: "Dubai",
    price: "2,150,000",
    priceQualifier: "AED",
    purpose: "For Sale",
    type: "Townhouse",
    constructionStatus: "Handed Over",
    bedrooms: 4,
    bathrooms: 4,
    area: "2,320 sq ft",
    floor: "Ground + 1",
    parking: "2 covered bays",
    furnishing: "Unfurnished",
    status: "Live",
    views: 331,
    enquiries: 21,
    published: "2026-05-27",
    description:
      "A family four-bedroom on a quiet interior road, backing onto landscaped open space rather than another row of units. Priced for a genuine sale rather than a test of the market, and the seller is flexible on handover timing for a school-term move.",
    highlights: [
      "Backs onto green space",
      "Motivated seller",
      "Family community with schools",
      "Maid's room + study",
    ],
    images: gallery(4),
    developer: "Damac",
    ownership: "Freehold",
    expectedYield: "6.8%",
    serviceCharge: "AED 3.5 / sq ft",
    reraVerified: true,
    commissionCovered: false,
    amenities: [
      "Community pool",
      "Padel courts",
      "Cycling track",
      "Nursery and schools",
    ],
  },
  {
    id: "rbr-004",
    slug: "jvc-studio-rental",
    title: "Jumeirah Village Circle — Studio",
    location: "Jumeirah Village Circle, Dubai",
    locality: "Jumeirah Village Circle",
    community: "Jumeirah Village Circle",
    emirate: "Dubai",
    price: "62,000",
    priceQualifier: "AED / year",
    purpose: "For Rent",
    type: "Apartment",
    constructionStatus: "Handed Over",
    bedrooms: 0,
    bathrooms: 1,
    area: "430 sq ft",
    floor: "9 of 22",
    parking: "1 allocated bay",
    furnishing: "Furnished",
    status: "Live",
    views: 187,
    enquiries: 9,
    published: "2026-07-04",
    description:
      "A fully furnished studio available now, chiller included in the rent. Landlord will consider up to four cheques, which is unusually flexible for this price band in JVC.",
    highlights: [
      "Chiller included",
      "Up to 4 cheques",
      "Available immediately",
      "Fully furnished",
    ],
    images: gallery(1),
    ownership: "Freehold",
    reraVerified: true,
    commissionCovered: false,
    amenities: ["Shared pool", "Gymnasium", "Covered parking", "24/7 security"],
  },
  {
    id: "rbr-005",
    slug: "palm-jumeirah-3br-penthouse",
    title: "Palm Jumeirah — 3 Bed Penthouse",
    location: "Palm Jumeirah, Dubai",
    locality: "Palm Jumeirah",
    community: "Palm Jumeirah",
    emirate: "Dubai",
    price: "12,900,000",
    priceQualifier: "AED",
    purpose: "For Sale",
    type: "Penthouse",
    constructionStatus: "Handed Over",
    bedrooms: 3,
    bathrooms: 4,
    area: "3,650 sq ft",
    floor: "Top floor",
    parking: "3 covered bays",
    furnishing: "Furnished",
    status: "Live",
    views: 524,
    enquiries: 27,
    published: "2026-04-19",
    description:
      "A full-floor penthouse on the Palm with a private roof terrace and skyline views back toward Marina. Sold furnished as presented. Viewings are by appointment only and the unit is currently tenanted until the end of the year.",
    highlights: [
      "Private roof terrace",
      "Sold furnished",
      "Full-floor layout",
      "Skyline and sea aspect",
    ],
    images: gallery(3),
    developer: "Nakheel",
    ownership: "Freehold",
    expectedYield: "5.2%",
    serviceCharge: "AED 22 / sq ft",
    reraVerified: true,
    featured: true,
    commissionCovered: false,
    amenities: [
      "Private beach",
      "Residents' spa",
      "Valet parking",
      "Temperature-controlled pool",
    ],
  },
  {
    id: "rbr-006",
    slug: "business-bay-office-floor",
    title: "Business Bay — Fitted Office Floor",
    location: "Business Bay, Dubai",
    locality: "Business Bay",
    community: "Business Bay",
    emirate: "Dubai",
    price: "4,800,000",
    priceQualifier: "AED",
    purpose: "For Sale",
    type: "Office",
    constructionStatus: "Handed Over",
    bedrooms: 0,
    bathrooms: 2,
    area: "2,900 sq ft",
    floor: "14 of 30",
    parking: "4 covered bays",
    furnishing: "Fitted",
    status: "Live",
    views: 143,
    enquiries: 6,
    published: "2026-06-30",
    description:
      "A fitted office floor with an existing tenant in place on a three-year lease, so it transfers as an income-producing asset rather than an empty shell. Canal-facing on the higher side of the floorplate.",
    highlights: [
      "Tenanted — income producing",
      "Fitted and partitioned",
      "Canal aspect",
      "4 parking bays included",
    ],
    images: gallery(5),
    ownership: "Freehold",
    expectedYield: "8.2%",
    serviceCharge: "AED 16 / sq ft",
    reraVerified: true,
    commissionCovered: false,
    amenities: ["Reception", "Meeting suites", "Retail podium", "Metro nearby"],
  },
];
