/**
 * Demo inventory shown when no Supabase/Blob listings are published yet.
 *
 * Real published listings always take precedence — these only fill the
 * portfolio so the product is reviewable before inventory is loaded.
 */

const img = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1400&q=80`;

const INTERIORS = [
  "1545324418-cc1a3fa10c00",
  "1502672260266-1c1ef2d93688",
  "1522708323590-d24dbb6b0267",
  "1560448204-e02f11c3d0e2",
  "1493809842364-78817add7ffb",
  "1560185007-cde436f6a4d0",
];

const gallery = (offset: number) =>
  [0, 1, 2].map((i) => img(INTERIORS[(offset + i) % INTERIORS.length]));

const RAW_SEEDS = [
  {
    id: "rbr-001",
    slug: "marina-vista-2br-emaar-beachfront",
    title: "Marina Vista — 2 Bed Sea View",
    location: "Emaar Beachfront, Dubai",
    locality: "Emaar Beachfront",
    community: "Emaar Beachfront",
    emirate: "Dubai",
    price: "3,450,000",
    priceQualifier: "AED",
    originalPrice: "2,780,000",
    purpose: "For Sale",
    type: "Apartment",
    constructionStatus: "Handed Over",
    bedrooms: 2,
    bathrooms: 3,
    area: "1,180 sq ft",
    floor: "32 of 60",
    parking: "1 covered bay",
    furnishing: "Unfurnished",
    status: "Live",
    views: 412,
    enquiries: 18,
    published: "2026-06-02",
    description:
      "A corner two-bedroom on a high floor at Marina Vista, with uninterrupted views across the Gulf and the marina skyline. Handed over and vacant on transfer, so it suits either an end-user moving in directly or an investor targeting short-let yield on a beachfront address.",
    highlights: [
      "Direct private beach access",
      "Vacant on transfer",
      "Corner layout with dual aspect",
      "Emaar-managed building",
    ],
    images: gallery(0),
    developer: "Emaar",
    ownership: "Freehold",
    expectedYield: "6.4%",
    serviceCharge: "AED 18 / sq ft",
    reraVerified: true,
    featured: true,
    commissionCovered: false,
    amenities: [
      "Private beach",
      "Infinity pool",
      "Gymnasium",
      "24/7 concierge",
      "Covered parking",
    ],
  },
  {
    id: "rbr-002",
    slug: "creek-waters-1br-off-plan",
    title: "Creek Waters — 1 Bed Off-Plan",
    location: "Dubai Creek Harbour, Dubai",
    locality: "Dubai Creek Harbour",
    community: "Dubai Creek Harbour",
    emirate: "Dubai",
    price: "1,620,000",
    priceQualifier: "AED",
    originalPrice: "1,455,000",
    purpose: "For Sale",
    type: "Apartment",
    constructionStatus: "Off-plan",
    possessionMonth: "September",
    possessionYear: 2027,
    bedrooms: 1,
    bathrooms: 2,
    area: "745 sq ft",
    floor: "18 of 40",
    parking: "1 allocated bay",
    furnishing: "Unfurnished",
    status: "Live",
    views: 268,
    enquiries: 12,
    published: "2026-06-18",
    description:
      "An entry-price one-bedroom in Emaar's Creek Waters tower, overlooking the creek promenade. The payment plan carries 20% past handover, which keeps the cash requirement low through construction and suits buyers building a Dubai portfolio gradually.",
    highlights: [
      "80/20 payment plan",
      "20% post-handover over 2 years",
      "Creek promenade frontage",
      "Q3 2027 handover",
    ],
    images: gallery(2),
    developer: "Emaar",
    ownership: "Freehold",
    expectedYield: "7.1%",
    handover: "Q3 2027",
    projectStage: "Under construction",
    paymentPlan: "80/20 with post-handover",
    paymentMilestones: [
      { label: "On booking", percentage: 10 },
      { label: "During construction", percentage: 70 },
      { label: "Post-handover (24 months)", percentage: 20 },
    ],
    postHandoverPaymentPlan: true,
    commissionCovered: true,
    reraVerified: true,
    featured: true,
    amenities: [
      "Infinity pool",
      "Creek-facing podium",
      "Kids play area",
      "Retail promenade",
    ],
  },
  {
    id: "rbr-003",
    slug: "damac-hills-2-4br-townhouse",
    title: "Damac Hills 2 — 4 Bed Townhouse",
    location: "Damac Hills 2, Dubai",
    locality: "Damac Hills 2",
    community: "Damac Hills",
    emirate: "Dubai",
    price: "2,150,000",
    priceQualifier: "AED",
    originalPrice: "1,690,000",
    purpose: "For Sale",
    type: "Townhouse",
    constructionStatus: "Handed Over",
    bedrooms: 4,
    bathrooms: 4,
    area: "2,320 sq ft",
    floor: "Ground + 1",
    parking: "2 covered bays",
    furnishing: "Unfurnished",
    status: "Live",
    views: 331,
    enquiries: 21,
    published: "2026-05-27",
    description:
      "A family four-bedroom on a quiet interior road, backing onto landscaped open space rather than another row of units. Priced for a genuine sale rather than a test of the market, and the seller is flexible on handover timing for a school-term move.",
    highlights: [
      "Backs onto green space",
      "Motivated seller",
      "Family community with schools",
      "Maid's room + study",
    ],
    images: gallery(4),
    developer: "Damac",
    ownership: "Freehold",
    expectedYield: "6.8%",
    serviceCharge: "AED 3.5 / sq ft",
    reraVerified: true,
    commissionCovered: false,
    amenities: [
      "Community pool",
      "Padel courts",
      "Cycling track",
      "Nursery and schools",
    ],
  },
  {
    id: "rbr-004",
    slug: "jvc-studio-rental",
    title: "Jumeirah Village Circle — Studio",
    location: "Jumeirah Village Circle, Dubai",
    locality: "Jumeirah Village Circle",
    community: "Jumeirah Village Circle",
    emirate: "Dubai",
    price: "62,000",
    priceQualifier: "AED / year",
    purpose: "For Rent",
    type: "Apartment",
    constructionStatus: "Handed Over",
    bedrooms: 0,
    bathrooms: 1,
    area: "430 sq ft",
    floor: "9 of 22",
    parking: "1 allocated bay",
    furnishing: "Furnished",
    status: "Live",
    views: 187,
    enquiries: 9,
    published: "2026-07-04",
    description:
      "A fully furnished studio available now, chiller included in the rent. Landlord will consider up to four cheques, which is unusually flexible for this price band in JVC.",
    highlights: [
      "Chiller included",
      "Up to 4 cheques",
      "Available immediately",
      "Fully furnished",
    ],
    images: gallery(1),
    ownership: "Freehold",
    reraVerified: true,
    commissionCovered: false,
    amenities: ["Shared pool", "Gymnasium", "Covered parking", "24/7 security"],
  },
  {
    id: "rbr-005",
    slug: "palm-jumeirah-3br-penthouse",
    title: "Palm Jumeirah — 3 Bed Penthouse",
    location: "Palm Jumeirah, Dubai",
    locality: "Palm Jumeirah",
    community: "Palm Jumeirah",
    emirate: "Dubai",
    price: "12,900,000",
    priceQualifier: "AED",
    originalPrice: "9,900,000",
    purpose: "For Sale",
    type: "Penthouse",
    constructionStatus: "Handed Over",
    bedrooms: 3,
    bathrooms: 4,
    area: "3,650 sq ft",
    floor: "Top floor",
    parking: "3 covered bays",
    furnishing: "Furnished",
    status: "Live",
    views: 524,
    enquiries: 27,
    published: "2026-04-19",
    description:
      "A full-floor penthouse on the Palm with a private roof terrace and skyline views back toward Marina. Sold furnished as presented. Viewings are by appointment only and the unit is currently tenanted until the end of the year.",
    highlights: [
      "Private roof terrace",
      "Sold furnished",
      "Full-floor layout",
      "Skyline and sea aspect",
    ],
    images: gallery(3),
    developer: "Nakheel",
    ownership: "Freehold",
    expectedYield: "5.2%",
    serviceCharge: "AED 22 / sq ft",
    reraVerified: true,
    featured: true,
    commissionCovered: false,
    amenities: [
      "Private beach",
      "Residents' spa",
      "Valet parking",
      "Temperature-controlled pool",
    ],
  },
  {
    id: "rbr-006",
    slug: "business-bay-office-floor",
    title: "Business Bay — Fitted Office Floor",
    location: "Business Bay, Dubai",
    locality: "Business Bay",
    community: "Business Bay",
    emirate: "Dubai",
    price: "4,800,000",
    priceQualifier: "AED",
    originalPrice: "3,950,000",
    purpose: "For Sale",
    type: "Office",
    constructionStatus: "Handed Over",
    bedrooms: 0,
    bathrooms: 2,
    area: "2,900 sq ft",
    floor: "14 of 30",
    parking: "4 covered bays",
    furnishing: "Fitted",
    status: "Live",
    views: 143,
    enquiries: 6,
    published: "2026-06-30",
    description:
      "A fitted office floor with an existing tenant in place on a three-year lease, so it transfers as an income-producing asset rather than an empty shell. Canal-facing on the higher side of the floorplate.",
    highlights: [
      "Tenanted — income producing",
      "Fitted and partitioned",
      "Canal aspect",
      "4 parking bays included",
    ],
    images: gallery(5),
    ownership: "Freehold",
    expectedYield: "8.2%",
    serviceCharge: "AED 16 / sq ft",
    reraVerified: true,
    commissionCovered: false,
    amenities: ["Reception", "Meeting suites", "Retail podium", "Metro nearby"],
  },
  {
    id: "rbr-007",
    slug: "downtown-1br-burj-view",
    title: "Downtown — 1 Bed Burj View",
    location: "Downtown Dubai, Dubai",
    locality: "Downtown Dubai",
    community: "Downtown Dubai",
    emirate: "Dubai",
    price: "1,950,000",
    priceQualifier: "AED",
    originalPrice: "1,640,000",
    purpose: "For Sale",
    type: "Apartment",
    constructionStatus: "Handed Over",
    bedrooms: 1,
    bathrooms: 2,
    area: "790 sq ft",
    floor: "24 of 46",
    parking: "1 covered bay",
    furnishing: "Furnished",
    status: "Live",
    views: 356,
    enquiries: 19,
    published: "2026-06-11",
    description:
      "A furnished one-bedroom with a direct Burj Khalifa view from the living room. Currently on a short-let licence returning above the building average, so it transfers either as an income unit or vacant for an end-user.",
    highlights: [
      "Direct Burj Khalifa view",
      "Short-let licence in place",
      "Furnished as seen",
      "Walk to Dubai Mall",
    ],
    images: gallery(3),
    developer: "Emaar",
    ownership: "Freehold",
    expectedYield: "7.4%",
    serviceCharge: "AED 22 / sq ft",
    reraVerified: true,
    commissionCovered: false,
    amenities: ["Infinity pool", "Gymnasium", "Concierge", "Boulevard access"],
  },
  {
    id: "rbr-008",
    slug: "jvc-1br-entry-investment",
    title: "Jumeirah Village Circle — 1 Bed",
    location: "Jumeirah Village Circle, Dubai",
    locality: "Jumeirah Village Circle",
    community: "Jumeirah Village Circle",
    emirate: "Dubai",
    price: "950,000",
    priceQualifier: "AED",
    originalPrice: "812,000",
    purpose: "For Sale",
    type: "Apartment",
    constructionStatus: "Handed Over",
    bedrooms: 1,
    bathrooms: 2,
    area: "712 sq ft",
    floor: "6 of 18",
    parking: "1 allocated bay",
    furnishing: "Unfurnished",
    status: "Live",
    views: 291,
    enquiries: 24,
    published: "2026-07-02",
    description:
      "The lowest entry into a freehold one-bedroom in the portfolio. Tenanted at AED 68,000 until March, so it produces from day one rather than sitting empty while you find a tenant.",
    highlights: [
      "Lowest entry price",
      "Tenanted until March",
      "Yield above 7%",
      "Freehold",
    ],
    images: gallery(1),
    ownership: "Freehold",
    expectedYield: "7.2%",
    serviceCharge: "AED 12 / sq ft",
    reraVerified: true,
    commissionCovered: true,
    amenities: ["Shared pool", "Gymnasium", "Covered parking", "Retail below"],
  },
  {
    id: "rbr-009",
    slug: "dubai-hills-3br-villa",
    title: "Dubai Hills Estate — 3 Bed Villa",
    location: "Dubai Hills Estate, Dubai",
    locality: "Dubai Hills Estate",
    community: "Dubai Hills Estate",
    emirate: "Dubai",
    price: "5,650,000",
    priceQualifier: "AED",
    originalPrice: "4,300,000",
    purpose: "For Sale",
    type: "Villa",
    constructionStatus: "Handed Over",
    bedrooms: 3,
    bathrooms: 4,
    area: "3,100 sq ft",
    floor: "Ground + 1",
    parking: "2 covered bays",
    furnishing: "Unfurnished",
    status: "Live",
    views: 402,
    enquiries: 22,
    published: "2026-05-30",
    description:
      "A three-bedroom villa on a landscaped plot backing onto the park rather than a neighbour. Walking distance to Dubai Hills Mall and the golf course, which is what holds value in this community.",
    highlights: [
      "Backs onto parkland",
      "Walk to Dubai Hills Mall",
      "Golf course community",
      "Maids room",
    ],
    images: gallery(4),
    developer: "Emaar",
    ownership: "Freehold",
    expectedYield: "5.8%",
    serviceCharge: "AED 4.5 / sq ft",
    reraVerified: true,
    featured: true,
    commissionCovered: false,
    amenities: ["Private garden", "Community pool", "Golf course", "Schools nearby"],
  },
  {
    id: "rbr-010",
    slug: "jbr-2br-sea-view",
    title: "JBR — 2 Bed Sea View",
    location: "Jumeirah Beach Residence, Dubai",
    locality: "Jumeirah Beach Residence",
    community: "Jumeirah Beach Residence",
    emirate: "Dubai",
    price: "2,650,000",
    priceQualifier: "AED",
    originalPrice: "2,180,000",
    purpose: "For Sale",
    type: "Apartment",
    constructionStatus: "Handed Over",
    bedrooms: 2,
    bathrooms: 3,
    area: "1,320 sq ft",
    floor: "17 of 40",
    parking: "1 covered bay",
    furnishing: "Furnished",
    status: "Live",
    views: 318,
    enquiries: 17,
    published: "2026-06-24",
    description:
      "Full sea view from the living room and both bedrooms, with direct access to The Walk and the beach. Strong short-let performer in season, and vacant on transfer if you want it yourself.",
    highlights: [
      "Full sea view",
      "Beach and The Walk access",
      "Vacant on transfer",
      "Furnished",
    ],
    images: gallery(0),
    ownership: "Freehold",
    expectedYield: "6.9%",
    serviceCharge: "AED 19 / sq ft",
    reraVerified: true,
    commissionCovered: false,
    amenities: ["Private beach", "Pool deck", "Gymnasium", "Retail promenade"],
  },
  {
    id: "rbr-011",
    slug: "creek-harbour-2br-off-plan",
    title: "Dubai Creek Harbour — 2 Bed Off-Plan",
    location: "Dubai Creek Harbour, Dubai",
    locality: "Dubai Creek Harbour",
    community: "Dubai Creek Harbour",
    emirate: "Dubai",
    price: "2,420,000",
    priceQualifier: "AED",
    originalPrice: "2,180,000",
    purpose: "For Sale",
    type: "Apartment",
    constructionStatus: "Off-plan",
    possessionMonth: "June",
    possessionYear: 2028,
    bedrooms: 2,
    bathrooms: 3,
    area: "1,140 sq ft",
    floor: "22 of 52",
    parking: "1 allocated bay",
    furnishing: "Unfurnished",
    status: "Live",
    views: 274,
    enquiries: 15,
    published: "2026-07-15",
    description:
      "A two-bedroom in the newest Creek Harbour release, facing the tower and the creek rather than inland. The 60/40 plan keeps the cash requirement light until handover in 2028.",
    highlights: [
      "60/40 payment plan",
      "Creek and tower view",
      "Q2 2028 handover",
      "New release pricing",
    ],
    images: gallery(2),
    developer: "Emaar",
    ownership: "Freehold",
    expectedYield: "6.6%",
    handover: "Q2 2028",
    projectStage: "Under construction",
    paymentPlan: "60/40 during construction",
    paymentMilestones: [
      { label: "On booking", percentage: 20 },
      { label: "During construction", percentage: 40 },
      { label: "On handover", percentage: 40 },
    ],
    reraVerified: true,
    commissionCovered: true,
    amenities: ["Creek promenade", "Infinity pool", "Kids play area", "Retail podium"],
  },
  {
    id: "rbr-012",
    slug: "arabian-ranches-4br-family-villa",
    title: "Arabian Ranches — 4 Bed Family Villa",
    location: "Arabian Ranches, Dubai",
    locality: "Arabian Ranches",
    community: "Arabian Ranches",
    emirate: "Dubai",
    price: "6,750,000",
    priceQualifier: "AED",
    originalPrice: "5,200,000",
    purpose: "For Sale",
    type: "Villa",
    constructionStatus: "Handed Over",
    bedrooms: 4,
    bathrooms: 5,
    area: "3,850 sq ft",
    floor: "Ground + 1",
    parking: "2 covered bays",
    furnishing: "Unfurnished",
    status: "Live",
    views: 367,
    enquiries: 20,
    published: "2026-05-18",
    description:
      "A four-bedroom on a corner plot with a private pool already installed. Established community with mature landscaping, which is the difference between this and a newer villa development at the same price.",
    highlights: [
      "Private pool installed",
      "Corner plot",
      "Mature community",
      "Schools within the community",
    ],
    images: gallery(5),
    developer: "Emaar",
    ownership: "Freehold",
    expectedYield: "5.4%",
    serviceCharge: "AED 3.8 / sq ft",
    reraVerified: true,
    commissionCovered: false,
    amenities: ["Private pool", "Golf club", "Community centre", "Cycling tracks"],
  },
  {
    id: "rbr-013",
    slug: "business-bay-1br-canal",
    title: "Business Bay — 1 Bed Canal View",
    location: "Business Bay, Dubai",
    locality: "Business Bay",
    community: "Business Bay",
    emirate: "Dubai",
    price: "1,350,000",
    priceQualifier: "AED",
    originalPrice: "1,120,000",
    purpose: "For Sale",
    type: "Apartment",
    constructionStatus: "Handed Over",
    bedrooms: 1,
    bathrooms: 2,
    area: "745 sq ft",
    floor: "19 of 35",
    parking: "1 allocated bay",
    furnishing: "Unfurnished",
    status: "Live",
    views: 248,
    enquiries: 13,
    published: "2026-07-08",
    description:
      "One-bedroom facing the canal, five minutes from Downtown without Downtown pricing. Vacant and ready, which suits either a first purchase or an addition to a rental portfolio.",
    highlights: [
      "Canal view",
      "Five minutes to Downtown",
      "Vacant and ready",
      "Under AED 1.5M",
    ],
    images: gallery(3),
    ownership: "Freehold",
    expectedYield: "7.0%",
    serviceCharge: "AED 15 / sq ft",
    reraVerified: true,
    commissionCovered: true,
    amenities: ["Canal promenade", "Pool", "Gymnasium", "Covered parking"],
  },
  {
    id: "rbr-014",
    slug: "dubai-south-2br-off-plan",
    title: "Dubai South — 2 Bed Off-Plan",
    location: "Dubai South, Dubai",
    locality: "Dubai South",
    community: "Dubai South",
    emirate: "Dubai",
    price: "1,180,000",
    priceQualifier: "AED",
    originalPrice: "1,050,000",
    purpose: "For Sale",
    type: "Apartment",
    constructionStatus: "Off-plan",
    possessionMonth: "December",
    possessionYear: 2027,
    bedrooms: 2,
    bathrooms: 2,
    area: "980 sq ft",
    floor: "9 of 15",
    parking: "1 allocated bay",
    furnishing: "Unfurnished",
    status: "Live",
    views: 186,
    enquiries: 11,
    published: "2026-07-21",
    description:
      "Two bedrooms near the Expo City site and the new metro extension. The cheapest off-plan two-bedroom here, on a plan that runs 1% monthly rather than a large lump at handover.",
    highlights: [
      "1% monthly payment plan",
      "Near Expo City and metro",
      "Q4 2027 handover",
      "Entry-level off-plan",
    ],
    images: gallery(1),
    ownership: "Freehold",
    expectedYield: "7.8%",
    handover: "Q4 2027",
    projectStage: "Under construction",
    paymentPlan: "1% monthly",
    paymentMilestones: [
      { label: "On booking", percentage: 10 },
      { label: "Monthly during construction", percentage: 60 },
      { label: "On handover", percentage: 30 },
    ],
    postHandoverPaymentPlan: true,
    reraVerified: true,
    commissionCovered: true,
    amenities: ["Pool", "Gymnasium", "Retail", "Metro nearby"],
  },
  {
    id: "rbr-015",
    slug: "marina-1br-rental",
    title: "Dubai Marina — 1 Bed Rental",
    location: "Dubai Marina, Dubai",
    locality: "Dubai Marina",
    community: "Dubai Marina",
    emirate: "Dubai",
    price: "115,000",
    priceQualifier: "AED / year",
    purpose: "For Rent",
    type: "Apartment",
    constructionStatus: "Handed Over",
    bedrooms: 1,
    bathrooms: 2,
    area: "820 sq ft",
    floor: "21 of 38",
    parking: "1 allocated bay",
    furnishing: "Furnished",
    status: "Live",
    views: 224,
    enquiries: 16,
    published: "2026-07-19",
    description:
      "Furnished one-bedroom on the marina walk, available now. Landlord will take four cheques and includes chiller, which is unusual at this price in Marina.",
    highlights: [
      "Chiller included",
      "Up to 4 cheques",
      "Marina walk location",
      "Available immediately",
    ],
    images: gallery(0),
    ownership: "Freehold",
    reraVerified: true,
    commissionCovered: false,
    amenities: ["Pool", "Gymnasium", "Marina walk", "24/7 security"],
  },
  {
    id: "rbr-016",
    slug: "downtown-2br-rental",
    title: "Downtown — 2 Bed Rental",
    location: "Downtown Dubai, Dubai",
    locality: "Downtown Dubai",
    community: "Downtown Dubai",
    emirate: "Dubai",
    price: "185,000",
    priceQualifier: "AED / year",
    purpose: "For Rent",
    type: "Apartment",
    constructionStatus: "Handed Over",
    bedrooms: 2,
    bathrooms: 3,
    area: "1,280 sq ft",
    floor: "31 of 52",
    parking: "2 allocated bays",
    furnishing: "Furnished",
    status: "Live",
    views: 268,
    enquiries: 14,
    published: "2026-07-12",
    description:
      "A high-floor two-bedroom with fountain views, fully furnished and available from next month. Two parking bays, which is rare in Downtown and worth real money if you have two cars.",
    highlights: [
      "Fountain view",
      "Two parking bays",
      "Fully furnished",
      "Available next month",
    ],
    images: gallery(2),
    developer: "Emaar",
    ownership: "Freehold",
    reraVerified: true,
    commissionCovered: false,
    amenities: ["Infinity pool", "Gymnasium", "Concierge", "Dubai Mall access"],
  },
];

/**
 * Every seed listing carries a dossier.
 *
 * The route builds the file on demand from the listing itself, so there is
 * nothing stored to point at — marking it ready is what surfaces the download
 * control. A listing published through Blob overwrites this with its own
 * generated file.
 */
export const SEED_PROPERTIES = RAW_SEEDS.map((property) => ({
  ...property,
  pdfUrl: `/dossier/${property.slug}`,
  pdfStatus: "ready" as const,
  brochure: {
    name: `${property.title} - project pack.pdf`,
    url: `/docs/${property.slug}-brochure.pdf`,
  },
  floorPlan: {
    name: `${property.title} - floor plan.pdf`,
    url: `/docs/${property.slug}-floor-plan.pdf`,
  },
}));
